
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HZT
 */
public class OperatorWindow extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindow
     */
    public OperatorWindow() {
        initComponents();
        getContentPane().setBackground(Color.black);
//        Date date=new Date();
//        DateFormat df=DateFormat.getDateInstance(DateFormat.FULL);
//        jLabel1.setText(df.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane19 = new javax.swing.JTabbedPane();
        jPanel23 = new javax.swing.JPanel();
        jTabbedPane20 = new javax.swing.JTabbedPane();
        jPanel24 = new javax.swing.JPanel();
        jTabbedPane21 = new javax.swing.JTabbedPane();
        jPanel25 = new javax.swing.JPanel();
        jTabbedPane22 = new javax.swing.JTabbedPane();
        jPanel26 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane14 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jTabbedPane23 = new javax.swing.JTabbedPane();
        jPanel27 = new javax.swing.JPanel();
        jTabbedPane24 = new javax.swing.JTabbedPane();
        jPanel28 = new javax.swing.JPanel();
        jTabbedPane25 = new javax.swing.JTabbedPane();
        jPanel29 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane26 = new javax.swing.JTabbedPane();
        jPanel30 = new javax.swing.JPanel();
        jTabbedPane27 = new javax.swing.JTabbedPane();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jTabbedPane28 = new javax.swing.JTabbedPane();
        jPanel34 = new javax.swing.JPanel();
        jTabbedPane29 = new javax.swing.JTabbedPane();
        jPanel35 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane15 = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        jTabbedPane16 = new javax.swing.JTabbedPane();
        jPanel20 = new javax.swing.JPanel();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        jTabbedPane18 = new javax.swing.JTabbedPane();
        jPanel22 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jTabbedPane13 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane11 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jTabbedPane12 = new javax.swing.JTabbedPane();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jFrame1.setUndecorated(true);
        jFrame1.setResizable(false);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiomedia/adminIcon (1).png"))); // NOI18N
        jFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        jTabbedPane3.setBackground(new java.awt.Color(32, 146, 210));
        jTabbedPane3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane19.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane20.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane21.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane22.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane22.addTab("Specific Record", jPanel26);

        jPanel25.add(jTabbedPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 200));

        jTabbedPane21.addTab("Covid Detail", jPanel25);

        jPanel24.add(jTabbedPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 240));

        jTabbedPane20.addTab("Doctor Detail", jPanel24);

        jPanel23.add(jTabbedPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 270));

        jTabbedPane19.addTab("Patient Detail", jPanel23);

        jPanel7.add(jTabbedPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 300));

        jTabbedPane3.addTab("VIEW", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane14.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane14MouseClicked(evt);
            }
        });

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane23.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane23MouseClicked(evt);
            }
        });

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane24.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane24MouseClicked(evt);
            }
        });

        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane25.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane25MouseClicked(evt);
            }
        });

        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane25.addTab("Diseases", jPanel29);

        jPanel28.add(jTabbedPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 210));

        jTabbedPane24.addTab("Medi-Claim", jPanel28);

        jPanel27.add(jTabbedPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 270));

        jTabbedPane23.addTab("Equipments", jPanel27);

        jPanel18.add(jTabbedPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 300));

        jTabbedPane14.addTab("Inventory", jPanel18);

        jPanel8.add(jTabbedPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 330));

        jTabbedPane3.addTab("STOCK", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane26.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane27.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane27.addTab("View Feedback", jPanel31);

        jPanel30.add(jTabbedPane27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 300));

        jTabbedPane26.addTab("View Complain", jPanel30);

        jPanel9.add(jTabbedPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 330));

        jTabbedPane3.addTab("ENQUIRY", jPanel9);

        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane3.addTab("BLOOD", jPanel32);

        jPanel33.setPreferredSize(new java.awt.Dimension(360, 400));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane28.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane28MouseClicked(evt);
            }
        });

        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane29.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane29MouseClicked(evt);
            }
        });
        jTabbedPane29.addTab("Sign Out", jPanel35);

        jPanel34.add(jTabbedPane29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 300));

        jTabbedPane28.addTab("Change Password", jPanel34);

        jPanel33.add(jTabbedPane28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 330));

        jTabbedPane3.addTab("SETTING", jPanel33);

        jFrame1.getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 670, 340));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MEDICARE");
        jFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 10, 160, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiomedia/closeIcon (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiomedia/OperatorIcon (1).jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jTabbedPane2.setBackground(new java.awt.Color(32, 146, 210));
        jTabbedPane2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane15.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane15MouseClicked(evt);
            }
        });

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane16.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane16MouseClicked(evt);
            }
        });

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane17.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane17MouseClicked(evt);
            }
        });

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane18.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane18MouseClicked(evt);
            }
        });

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane18.addTab("Specific Record", jPanel22);

        jPanel21.add(jTabbedPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 200));

        jTabbedPane17.addTab("Covid Detail", jPanel21);

        jPanel20.add(jTabbedPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 240));

        jTabbedPane16.addTab("Doctor Detail", jPanel20);

        jPanel19.add(jTabbedPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 270));

        jTabbedPane15.addTab("Patient Detail", jPanel19);

        jPanel2.add(jTabbedPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 300));

        jTabbedPane2.addTab("VIEW", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane6MouseClicked(evt);
            }
        });

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane7MouseClicked(evt);
            }
        });

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane8MouseClicked(evt);
            }
        });

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane13MouseClicked(evt);
            }
        });

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane13.addTab("Diseases", jPanel17);

        jPanel12.add(jTabbedPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 210));

        jTabbedPane8.addTab("Medi-Claim", jPanel12);

        jPanel11.add(jTabbedPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 270));

        jTabbedPane7.addTab("Equipments", jPanel11);

        jPanel10.add(jTabbedPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 300));

        jTabbedPane6.addTab("Inventory", jPanel10);

        jPanel3.add(jTabbedPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 330));

        jTabbedPane2.addTab("STOCK", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("BLOOD", jPanel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane10.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane10.addTab("View Feedback", jPanel14);

        jPanel13.add(jTabbedPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 300));

        jTabbedPane9.addTab("View Complain", jPanel13);

        jPanel4.add(jTabbedPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 110, 330));

        jTabbedPane2.addTab("ENQUIRY", jPanel4);

        jPanel6.setPreferredSize(new java.awt.Dimension(360, 400));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane11.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane11MouseClicked(evt);
            }
        });

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane12MouseClicked(evt);
            }
        });
        jTabbedPane12.addTab("Sign Out", jPanel16);

        jPanel15.add(jTabbedPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 300));

        jTabbedPane11.addTab("Change Password", jPanel15);

        jPanel6.add(jTabbedPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 330));

        jTabbedPane2.addTab("SETTING", jPanel6);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 670, 340));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEDICARE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 160, 30));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiomedia/OptionIcon (1).jpg"))); // NOI18N
        jMenu1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(53, 47));

        jMenuItem1.setText("LOG-OUT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane12MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane12MouseClicked

    private void jTabbedPane11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane11MouseClicked
        // TODO add your handling code here:
        new ChangePassword().setVisible(true);
        dispose();
    }//GEN-LAST:event_jTabbedPane11MouseClicked

    private void jTabbedPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane6MouseClicked
        // TODO add your handling code here:
        new InventoryDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_jTabbedPane6MouseClicked

    private void jTabbedPane7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane7MouseClicked
        // TODO add your handling code here:
        new EquipmentDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_jTabbedPane7MouseClicked

    private void jTabbedPane8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane8MouseClicked
        // TODO add your handling code here:
        new MediclaimDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_jTabbedPane8MouseClicked

    private void jTabbedPane13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane13MouseClicked
        // TODO add your handling code here:
        new DiseasesDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_jTabbedPane13MouseClicked

    private void jTabbedPane25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane25MouseClicked

    private void jTabbedPane24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane24MouseClicked

    private void jTabbedPane23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane23MouseClicked

    private void jTabbedPane14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane14MouseClicked

    private void jTabbedPane29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane29MouseClicked

    private void jTabbedPane28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane28MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTabbedPane15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane15MouseClicked
        // TODO add your handling code here:
        new PatientDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_jTabbedPane15MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int result=JOptionPane.showConfirmDialog(this,"Do You Want to Sign-Out?","SIGN OUT MESSAGE",JOptionPane.YES_NO_OPTION);
        if(result==0)
        {
            new LoginWindow().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTabbedPane16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane16MouseClicked
        // TODO add your handling code here:
        new DoctorDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_jTabbedPane16MouseClicked

    private void jTabbedPane17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane17MouseClicked
        // TODO add your handling code here:
        new CovidPatientDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_jTabbedPane17MouseClicked

    private void jTabbedPane18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane18MouseClicked
        // TODO add your handling code here:
        // Speacific Record Write Here:
    }//GEN-LAST:event_jTabbedPane18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperatorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane11;
    private javax.swing.JTabbedPane jTabbedPane12;
    private javax.swing.JTabbedPane jTabbedPane13;
    private javax.swing.JTabbedPane jTabbedPane14;
    private javax.swing.JTabbedPane jTabbedPane15;
    private javax.swing.JTabbedPane jTabbedPane16;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTabbedPane jTabbedPane18;
    private javax.swing.JTabbedPane jTabbedPane19;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane20;
    private javax.swing.JTabbedPane jTabbedPane21;
    private javax.swing.JTabbedPane jTabbedPane22;
    private javax.swing.JTabbedPane jTabbedPane23;
    private javax.swing.JTabbedPane jTabbedPane24;
    private javax.swing.JTabbedPane jTabbedPane25;
    private javax.swing.JTabbedPane jTabbedPane26;
    private javax.swing.JTabbedPane jTabbedPane27;
    private javax.swing.JTabbedPane jTabbedPane28;
    private javax.swing.JTabbedPane jTabbedPane29;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    // End of variables declaration//GEN-END:variables
}
